import { getSiteSettings } from "@/lib/db/queries/settings";
import { createHomeSectionAction, deleteHomeSectionAction, updateHomeSectionAction } from "./actions";

export const dynamic = "force-dynamic";

export default async function HomeSectionsPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const [settings, query] = await Promise.all([getSiteSettings(), searchParams]);
  return <main className="mx-auto max-w-6xl px-4 py-8"><p className="text-xs font-black uppercase tracking-[0.18em] text-[var(--accent)]">Content</p><h1 className="mt-1 text-3xl font-black">Homepage categories</h1><p className="mt-1 text-sm font-bold text-[var(--muted)]">Add, edit, hide, or delete homepage rails. Item count controls how many titles each category exposes.</p>
    {query.saved ? <Notice tone="success">Homepage category saved.</Notice> : null}{query.error === "last-section" ? <Notice tone="error">At least one homepage category must remain.</Notice> : null}{query.error && query.error !== "last-section" ? <Notice tone="error">Check the category fields and try again.</Notice> : null}
    <div className="mt-6 grid gap-4">{settings.homeSections.map((section) => <Card key={section.id} section={section} />)}<form action={createHomeSectionAction} className="rounded-2xl border border-dashed border-[var(--accent)] bg-[var(--surface)] p-5 shadow-sm"><h2 className="text-lg font-black">Add homepage category</h2><Fields /><button className="mt-4 rounded-xl bg-[var(--accent)] px-5 py-3 text-sm font-black text-white">Add category</button></form></div>
  </main>;
}

type Value = Awaited<ReturnType<typeof getSiteSettings>>["homeSections"][number];
function Card({ section }: { section: Value }) { return <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-sm"><form action={updateHomeSectionAction.bind(null, section.id)}><div className="flex items-center justify-between gap-3"><h2 className="font-black">{section.title}</h2><span className="rounded-full bg-[var(--surface-strong)] px-3 py-1 text-xs font-black">{section.itemCount} items</span></div><Fields section={section} /><button className="mt-4 rounded-xl bg-[var(--foreground)] px-5 py-3 text-sm font-black text-[var(--background)]">Save category</button></form><form action={deleteHomeSectionAction.bind(null, section.id)} className="mt-2"><button className="rounded-xl border border-red-300 px-4 py-2 text-sm font-black text-red-700">Delete category</button></form></div>; }
function Fields({ section }: { section?: Value }) { return <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Field label="Category title"><input name="title" required maxLength={80} defaultValue={section?.title} placeholder="Romance" className={inputClass} /></Field><Field label="Small label"><input name="subtitle" maxLength={80} defaultValue={section?.subtitle} placeholder="Updated" className={inputClass} /></Field><Field label="Content source"><select name="source" defaultValue={section?.source ?? "latest"} className={inputClass}><option value="popular">Popular manga</option><option value="latest">Latest manga</option><option value="adult">Adult manga</option><option value="tag">Tag category</option><option value="manhwa">Manhwa</option></select></Field><Field label="Tag slug"><input name="tag" defaultValue={section?.tag} placeholder="romance" className={inputClass} /></Field><Field label="Number shown"><input name="itemCount" type="number" min={1} max={30} defaultValue={section?.itemCount ?? 12} className={inputClass} /></Field><label className="flex items-center gap-2 text-sm font-black sm:col-span-2"><input type="checkbox" name="enabled" defaultChecked={section?.enabled ?? true} className="h-5 w-5 accent-[var(--accent)]" />Show this category</label></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1.5 text-sm font-black"><span>{label}</span>{children}</label>; }
function Notice({ tone, children }: { tone: "success" | "error"; children: React.ReactNode }) { return <p className={`mt-5 rounded-xl border p-4 text-sm font-bold ${tone === "success" ? "border-green-300 bg-green-50 text-green-800" : "border-red-300 bg-red-50 text-red-800"}`}>{children}</p>; }
const inputClass = "min-h-11 w-full rounded-xl border border-[var(--border)] bg-[var(--background)] px-3 py-2 font-medium";
