import Link from "next/link";
import { listReports } from "@/lib/db/queries/reports";
import { reviewReportAction } from "./actions";

export const dynamic = "force-dynamic";

export default async function ReportsPage({ searchParams }: { searchParams: Promise<{ status?: string; saved?: string; error?: string }> }) {
  const [reports, query] = await Promise.all([listReports(), searchParams]);
  const visible = query.status ? reports.filter((report) => report.status === query.status) : reports;
  const urgent = reports.filter((report) => report.priority === "urgent" && !["closed", "rejected"].includes(report.status)).length;
  return <main className="mx-auto max-w-6xl px-4 py-8"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[var(--accent)]">Trust & safety</p><h1 className="mt-1 text-3xl font-black">Reports</h1><p className="mt-1 text-sm text-[var(--muted)]">Review every notice manually. Report volume never removes content automatically.</p></div><span className={`rounded-full px-4 py-2 text-sm font-black ${urgent ? "bg-red-100 text-red-700" : "bg-green-100 text-green-700"}`}>{urgent} urgent</span></div>
  {query.saved ? <p className="mt-5 rounded-xl border border-green-300 bg-green-50 p-4 text-sm font-bold text-green-800">Report updated and audit log recorded.</p> : null}
  <nav className="mt-6 flex flex-wrap gap-2">{["", "new", "reviewing", "actioned", "rejected", "closed"].map((status) => <Link key={status || "all"} href={status ? `/manga1004/reports?status=${status}` : "/manga1004/reports"} className="rounded-full border border-[var(--border)] bg-[var(--surface)] px-3 py-2 text-xs font-black">{status || "all"} ({status ? reports.filter((r) => r.status === status).length : reports.length})</Link>)}</nav>
  <section className="mt-5 grid gap-4">{visible.length === 0 ? <p className="rounded-2xl border border-dashed p-8 text-center font-bold text-[var(--muted)]">No reports in this queue.</p> : visible.map((report) => <article key={report.id} className={`rounded-2xl border bg-[var(--surface)] p-5 shadow-sm ${report.priority === "urgent" ? "border-red-400" : "border-[var(--border)]"}`}><div className="flex flex-wrap gap-2"><Badge>{report.priority}</Badge><Badge>{report.reason.replaceAll("_", " ")}</Badge><Badge>{report.status}</Badge><span className="ml-auto text-xs font-bold text-[var(--muted)]">{new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(report.createdAt)}</span></div><h2 className="mt-4 font-black">{report.targetType}: {report.targetKey}</h2><a href={report.targetUrl} target="_blank" rel="noreferrer" className="mt-1 block truncate text-xs font-bold text-[var(--accent)]">{report.targetUrl}</a><p className="mt-4 whitespace-pre-wrap rounded-xl bg-[var(--background)] p-4 text-sm leading-6">{report.details}</p>{report.reason === "copyright" ? <dl className="mt-4 grid gap-2 rounded-xl border p-4 text-sm"><Row label="Reporter" value={report.reporterName} /><Row label="Email" value={report.reporterEmail} /><Row label="Rights holder" value={report.rightsHolder} /><Row label="Original work" value={report.originalWork} /><Row label="Signature" value={report.signature} /></dl> : null}<form action={reviewReportAction} className="mt-4 grid gap-3 sm:grid-cols-[180px_1fr_auto]"><input type="hidden" name="id" value={report.id} /><select name="status" defaultValue={report.status} className={inputClass}><option value="new">New</option><option value="reviewing">Reviewing</option><option value="actioned">Action taken</option><option value="rejected">Rejected</option><option value="closed">Closed</option></select><input name="resolution" required minLength={3} maxLength={5000} defaultValue={report.resolution ?? ""} placeholder="Record investigation and action taken…" className={inputClass} /><button className="rounded-xl bg-[var(--foreground)] px-4 py-2 text-sm font-black text-[var(--background)]">Save review</button></form></article>)}</section></main>;
}

function Badge({ children }: { children: React.ReactNode }) { return <span className="rounded-full bg-[var(--surface-strong)] px-2.5 py-1 text-[10px] font-black uppercase">{children}</span>; }
function Row({ label, value }: { label: string; value: string | null }) { return <div><dt className="text-xs font-black uppercase text-[var(--muted)]">{label}</dt><dd className="mt-0.5 whitespace-pre-wrap">{value || "—"}</dd></div>; }
const inputClass = "min-h-11 rounded-xl border border-[var(--border)] bg-[var(--background)] px-3 py-2 text-sm font-medium";
